### PR TITLE
Default window and pane

### PR DESCRIPTION
**Pull request by LovecraftianHorror**
**Note: this does impact what's accepted as a valid project file**

So I was working on allowing for `Default` values for `Window` and `Pane` I was wondering why `name` is required, but not in `Pane`. If `name` was also an option in `Window` then it would allow for a project file that's just

```toml
layout = "main-horizontal"
name = "example"
pane_name_user_option = "custom_pane_title"
start_directory = "/home/peter/projects/vim"
```

which is pretty bare-bones. I doubt many people would have a project file that just spawns one window with one pane, but this matches the behavior that a window with no panes still technically has one pane, so this was extended to a session with no windows still has the `Default` window. It looks like a unit test already exists for this behavior (in `it_uses_configs_start_directory_when_no_window_start_directory_present_for_session_start_directory`) so this PR would actually allow for that behavior to be used.

This is mostly just setting some foundation for trying to simplify `run` a window missing any panes will still get the default pane and the session having no windows will still get the default window, so with this change, the code can now easily reflect this same behavior.

### CODE REVIEW

**Comment by ethagnawl** [comment]
> I was wondering why name is required, but not in Pane.

This was just something I didn't get around to addressing. It's mentioned in the README and it'd be great to make this option available.

> I doubt many people would have a project file that just spawns one window with one pane ...

You might be surprised. I know people have mentioned similar setups in various tmuxinator issues and feature requests. For one, it provides a starting point for doing sysadmin tasks. It's also useful for people who use different ecosystems and versions of each, like Ruby and a particular version via RVM.

**Comment by LovecraftianHorror** [comment]
That's cool to hear! I'm glad that the change may actually have a meaningful impact, I just wanted to set up for simplifying some of the logic.

**Comment by ethagnawl** [comment]
@LovecraftianHorror I'll fix the conflicts I just introduced by merging #10.

**Comment by ethagnawl** [comment]
@LovecraftianHorror We stepped on each others toes with those merge conflicts. :package: 

I added an additional test and removed the related TODO from the README. I'll kick it back to you for review. (I added you to the repository as a collaborator, so you should now be able to merge PRs.)

**Pull request merged**
